package com.treasure.parttimejob.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.treasure.parttimejob.ui.model.PartTimeBean;
import com.treasure.parttimejob.mvp.model.UserInfo;
import com.treasure.parttimejob.ui.model.MsgBean;

import com.treasure.parttimejob.db.greendao.PartTimeBeanDao;
import com.treasure.parttimejob.db.greendao.UserInfoDao;
import com.treasure.parttimejob.db.greendao.MsgBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig partTimeBeanDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig msgBeanDaoConfig;

    private final PartTimeBeanDao partTimeBeanDao;
    private final UserInfoDao userInfoDao;
    private final MsgBeanDao msgBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        partTimeBeanDaoConfig = daoConfigMap.get(PartTimeBeanDao.class).clone();
        partTimeBeanDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        msgBeanDaoConfig = daoConfigMap.get(MsgBeanDao.class).clone();
        msgBeanDaoConfig.initIdentityScope(type);

        partTimeBeanDao = new PartTimeBeanDao(partTimeBeanDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        msgBeanDao = new MsgBeanDao(msgBeanDaoConfig, this);

        registerDao(PartTimeBean.class, partTimeBeanDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(MsgBean.class, msgBeanDao);
    }
    
    public void clear() {
        partTimeBeanDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        msgBeanDaoConfig.clearIdentityScope();
    }

    public PartTimeBeanDao getPartTimeBeanDao() {
        return partTimeBeanDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public MsgBeanDao getMsgBeanDao() {
        return msgBeanDao;
    }

}
